#############################################################################
# Makefile for building: imglabeller
# Generated by qmake (2.01a) (Qt 4.6.2) on: Fri Oct 21 11:42:47 2011
# Project:  imglabeller.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile imglabeller.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		img_label.cpp \
		state_variable.cpp \
		infer_engine.cpp \
		act_predict.cpp moc_mainwindow.cpp \
		moc_img_label.cpp \
		moc_state_variable.cpp \
		moc_infer_engine.cpp \
		moc_act_predict.cpp \
		qrc_rsc.cpp
OBJECTS       = main.o \
		mainwindow.o \
		img_label.o \
		state_variable.o \
		infer_engine.o \
		act_predict.o \
		moc_mainwindow.o \
		moc_img_label.o \
		moc_state_variable.o \
		moc_infer_engine.o \
		moc_act_predict.o \
		qrc_rsc.o
DIST          = /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		imglabeller.pro
QMAKE_TARGET  = imglabeller
DESTDIR       = 
TARGET        = imglabeller

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: imglabeller.pro  /usr/lib64/qt4/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile imglabeller.pro
/usr/lib64/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile imglabeller.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/imglabeller1.0.0 || $(MKDIR) .tmp/imglabeller1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/imglabeller1.0.0/ && $(COPY_FILE) --parents mainwindow.h img_label.h state_variable.h infer_engine.h act_predict.h .tmp/imglabeller1.0.0/ && $(COPY_FILE) --parents rsc.qrc .tmp/imglabeller1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp img_label.cpp state_variable.cpp infer_engine.cpp act_predict.cpp .tmp/imglabeller1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/imglabeller1.0.0/ && (cd `dirname .tmp/imglabeller1.0.0` && $(TAR) imglabeller1.0.0.tar imglabeller1.0.0 && $(COMPRESS) imglabeller1.0.0.tar) && $(MOVE) `dirname .tmp/imglabeller1.0.0`/imglabeller1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/imglabeller1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_img_label.cpp moc_state_variable.cpp moc_infer_engine.cpp moc_act_predict.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_img_label.cpp moc_state_variable.cpp moc_infer_engine.cpp moc_act_predict.cpp
moc_mainwindow.cpp: img_label.h \
		act_predict.h \
		infer_engine.h \
		state_variable.h \
		mainwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_img_label.cpp: img_label.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) img_label.h -o moc_img_label.cpp

moc_state_variable.cpp: state_variable.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) state_variable.h -o moc_state_variable.cpp

moc_infer_engine.cpp: state_variable.h \
		infer_engine.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) infer_engine.h -o moc_infer_engine.cpp

moc_act_predict.cpp: infer_engine.h \
		state_variable.h \
		act_predict.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) act_predict.h -o moc_act_predict.cpp

compiler_rcc_make_all: qrc_rsc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rsc.cpp
qrc_rsc.cpp: rsc.qrc \
		images/add.png \
		images/Exit.png \
		images/delete.png \
		images/open.png \
		images/save.png \
		images/zoomin.png \
		images/zoomreset.png \
		images/zoomout.png
	/usr/lib64/qt4/bin/rcc -name rsc rsc.qrc -o qrc_rsc.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib64/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		img_label.h \
		act_predict.h \
		infer_engine.h \
		state_variable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		img_label.h \
		act_predict.h \
		infer_engine.h \
		state_variable.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

img_label.o: img_label.cpp img_label.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o img_label.o img_label.cpp

state_variable.o: state_variable.cpp state_variable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o state_variable.o state_variable.cpp

infer_engine.o: infer_engine.cpp infer_engine.h \
		state_variable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o infer_engine.o infer_engine.cpp

act_predict.o: act_predict.cpp act_predict.h \
		infer_engine.h \
		state_variable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o act_predict.o act_predict.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_img_label.o: moc_img_label.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_img_label.o moc_img_label.cpp

moc_state_variable.o: moc_state_variable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_state_variable.o moc_state_variable.cpp

moc_infer_engine.o: moc_infer_engine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_infer_engine.o moc_infer_engine.cpp

moc_act_predict.o: moc_act_predict.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_act_predict.o moc_act_predict.cpp

qrc_rsc.o: qrc_rsc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rsc.o qrc_rsc.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

